---
- name: Installazione di Caddy su Debian
  hosts: all
  become: true

  tasks:
    - name: Installa pacchetti richiesti
      apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl
        state: present
        update_cache: yes

    - name: Scarica la chiave GPG di Caddy
      ansible.builtin.shell: |
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    - name: Aggiunge repository Caddy alla sources.list.d
      ansible.builtin.get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
        dest: /etc/apt/sources.list.d/caddy-stable.list
        mode: '0644'

    - name: Imposta permessi sulla chiave GPG
      ansible.builtin.file:
        path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        mode: '0644'

    - name: Imposta permessi sulla lista del repository
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/caddy-stable.list
        mode: '0644'

    - name: Aggiorna cache APT
      apt:
        update_cache: yes

    - name: Installa Caddy
      apt:
        name: caddy
        state: present
